stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/raw
    - src/features/feature_engineering.py
    outs:
    - data/processed
  missing_value_imputation:
    cmd: python src/imputation/missing_value_imputation.py
    deps:
    - data/processed
    - src/imputation/missing_value_imputation.py
    outs:
    - data/imputations
  model_prediction:
    cmd: python src/models/model_prediction.py
    deps:
    - data/imputations
    - src/models/model_prediction.py
    outs:
    - model.pkl
  model_submission:
    cmd: python src/models/model_submission.py
    deps:
    - model.pkl
    - src/models/model_submission.py
    outs:
    - data/submission
